name: 'Upload a Build Artifact'
description: 'Upload a build artifact that can be used by subsequent workflow steps'
author: 'GitHub'
inputs: 
  name:
    description: "Artifact name. If omitted, falls back to 'artifact' name. If empty string, it tries to upload the artifacts with the original file name."
    required: false
  path:
    description: 'A file, directory or wildcard pattern that describes what to upload'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'